name: complete-ci

on:
  workflow_dispatch:
  #push:
    #branches: ["main"]

jobs:
    sonarqube:
        runs-on: [self-hosted ,Linux]
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v6
    
          - name: Sonarqube scan
            uses: SonarSource/sonarqube-scan-action@v6.0.0
            with:
              args: >
                -Dsonar.projectKey=app.js
                -Dsonar.sources=.
                -Dsonar.qualitygate.wait=true
            env:
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    build:
      needs: sonarqube
      runs-on: [self-hosted ,Linux]

      steps:
        - name: checkout code
          uses: actions/checkout@v6

        - name: node modules install and Build
          run: |
            npm i
            npm run build


    test:
      needs: build
      runs-on: [self-hosted ,Linux]
      if: ${{ needs.build.result == 'success' }}
      

      steps:
        - name: checkout code
          uses: actions/checkout@v6

        - name: Test case run
          run: |
            npm i
            npm test



    login:
      needs: test
      runs-on: [self-hosted ,Linux]
      if: ${{ needs.test.result == 'success' }}
      env:
        image_tag: ${{ github.sha }}
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v4
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
         
        - name: docker image build
          run: docker build -f Dockerfile -t dockerfile-image .

        - name: docker image tag
          run: docker tag dockerfile-image ${{ vars.DOCKERHUB_USERNAME }}/testing-lab:$image_tag        
        

        - name: docker image push
          run: docker push ${{ vars.DOCKERHUB_USERNAME }}/testing-lab:$image_tag        
        
      

